$(function(){var config={apiKey:"AIzaSyBhveORgX2e5KZIJAb9JTsP8YZ4T5W_31I",authDomain:"twist-a-rama.firebaseapp.com",databaseURL:"https://twist-a-rama.firebaseio.com",projectId:"twist-a-rama",storageBucket:"twist-a-rama.appspot.com",messagingSenderId:"612426352757"};firebase.initializeApp(config);var database=firebase.database();function userCreateVars(userId){firebase.database().ref('users/'+userId).set({nvr:0,nvr_correct:0,math:0,math_correct:0,vr:0,vr_correct:0,displayName:firebase.auth().currentUser.displayName});}
$("#btnSignUp").click(function(){var email=$("#txtEmail").val();var pass=$("#txtPassword").val();var cPass=$("#txtPasswordConfirm").val();if(cPass==pass){firebase.auth().createUserWithEmailAndPassword(email,pass).catch(function(error){var errorCode=error.code;var errorMessage=error.message;$("#txtError").css("display","block");if(errorCode==='auth/email-already-in-use'){$("#txtError").text("There is already an account with that email");}else
if(errorCode==='auth/user-disabled'){$("#txtError").text("Your account has been disabled");}else
if(errorCode==='auth/user-not-found'){$("#txtError").text("Internal Error");}else
if(errorCode==='auth/weak-password'){$("#txtError").text("Password must be 6 characters long or more");}else
if(errorCode==='auth/invalid-email'){$("#txtError").text("Please enter a vaild email");}else
if(errorCode==='auth/email-already-in-use'){$("#txtError").text("There is already an account with that email");}else
if(errorCode==='auth/email-already-in-use'){$("#txtError").text("There is already an account with that email");}else
if(errorCode==='auth/email-already-in-use'){$("#txtError").text("There is already an account with that email");}else{$("#txtError").text(errorMessage);}});var user=firebase.auth().currentUser;}else{$("#txtError").css("display","block");$("#txtError").text("Passwords do not match");}
var stopListening=firebase.auth().onAuthStateChanged(function(user){var user=firebase.auth().currentUser;var database=firebase.database();if(user){var displayName=user.displayName;var email=user.email;var emailVerified=user.emailVerified;var photoURL=user.photoURL;var isAnonymous=user.isAnonymous;var uid=user.uid;var providerData=user.providerData;console.log(uid);console.log(email);user.updateProfile({displayName:$("#fname").val().concat(" ").concat($("#lname").val())});dispName=$("#fname").val().concat(" ").concat($("#lname").val());console.log(dispName);firebase.database().ref("users/"+firebase.auth().currentUser.uid).child("displayName").set(dispName);userCreateVars(user.uid);user.sendEmailVerification().then(function(){console.log("Verification Email Sent Succesfully!");window.location="/verify.html";}).catch(function(error){console.log("An error occured when sending a Verification Email :-( .");});userCreateVars(user.uid);$("#btnLogOut").show();stopListening();}else{}});});$("#btnLogOut").click(function(){$("#btnLogOut").hide();firebase.auth().signOut();});$("#btnLogin").click(function(){var email=$("#txtEmail").val();var pass=$("#txtPassword").val();firebase.auth().signInWithEmailAndPassword(email,pass);firebase.auth().onAuthStateChanged(function(user){var user=firebase.auth().currentUser;var database=firebase.database();if(user){var displayName=user.displayName;var email=user.email;var emailVerified=user.emailVerified;var photoURL=user.photoURL;var isAnonymous=user.isAnonymous;var uid=user.uid;var providerData=user.providerData;console.log(uid);console.log(email);if(user.emailVerified==true){window.location="/learn/browse.html";}else{window.location="/verify.html";}}else{}});});});
